SEED_NUMBER              : 0
USE_CUDA                 : True

DATASET_NAME             : "COCO" # Options: "COCO"
NUM_CLASSES              : 80 # Number of classes in dataset

MODEL_CHOICE             : "yolov5" # Option:"resnet" "vgg"
MODEL_VARIANT            : "yolov5s" # Common Options: "resnet50" "resnet18" "vgg11" For more options explore files in models to find the different options.

MODEL_SELECTION_FLAG     : 0 # create an untrained model = 0, start from a pytorch trained model = 1, start from a previously saved local model = 2

NUM_EPOCHS               : 30
LEARNING_RATE            : 1.0e-2 # for imagenet use 1.0e-5, otherwise 1.0e-2
