SEED_NUMBER              : 0
USE_CUDA                 : True

DATASET_NAME             : "ImageNet" # Options: "CIFAR10" "CIFAR100" "TinyImageNet"  "ImageNet"
NUM_CLASSES              : 1000 # Number of classes in dataset

MODEL_CHOICE             : "resnet" # Option:"resnet" "vgg"
MODEL_VARIANT            : "resnet18" # Common Options: "resnet50" "resnet18" "vgg11" For more options explore files in models to find the different options.

MODEL_SELECTION_FLAG     : 1 # create an untrained model = 0, start from a pytorch trained model = 1, start from a previously saved local model = 2

NUM_EPOCHS               : 5
LEARNING_RATE            : 1.0e-5 # for imagenet use 1.0e-5, otherwise 1.0e-2