SEED_NUMBER                      : 0
USE_CUDA                         : True # When doing quantisation set to False as only works with CPU at the moment.

DATASET_NAME                     : "CIFAR10" # Options: "CIFAR10" "CIFAR100" "TinyImageNet"  "ImageNet"
NUM_CLASSES                      : 10 # Number of classes in dataset

MODEL_CHOICE                     : "resnet" # Option:"resnet" "vgg"
MODEL_VARIANT                    : "resnet18" # Common Options: "resnet18" "vgg11" For more options explore files in models to find the different options.

COMPRESSION_TECHNIQUE            : "GUP_R"      # Option: "PTQ" "QAT" "GUP_R" "GUP_L1"

