SEED_NUMBER              : 0
USE_CUDA                 : True

DATASET_NAME             : "ImageNet" # Options: "CIFAR10" "CIFAR100" "TinyImageNet"  "ImageNet"
NUM_CLASSES              : 1000 # Number of classes in dataset

MODEL_CHOICE             : "resnet" # Option:"resnet" "vgg"
MODEL_VARIANT            : "resnet18" # Common Options: "resnet50" "resnet18" "vgg11" For more options explore files in models to find the different options.

COMPRESSION_TECHNIQUE    : "QAT"      # Option: "PTQ" "QAT" "GUP_R" "GUP_L1"

