SEED_NUMBER              : 0
USE_CUDA                 : True

DATASET_NAME             : "CIFAR10" # Options: "CIFAR10" "CIFAR100" "TinyImageNet"  "ImageNet"
NUM_CLASSES              : 10 # Number of classes in dataset

MODEL_CHOICE             : "resnet" # Option:"resnet" "vgg"
MODEL_VARIANT            : "resnet18" # Common Options: "resnet50" "resnet18" "vgg11" For more options explore files in models to find the different options.

COMPRESSION_TECHNIQUE    : "BNN"      # Option: "PTQ" "QAT" "GUP_R" "GUP_L1"

NUM_EPOCHS               : 5
LEARNING_RATE            : 1.0e-2 # for imagenet use 1.0e-5, otherwise 1.0e-2
